import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="flex flex-col min-h-screen">
                <main className="flex-1">
                    {children}
                </main>

                <footer className="bg-black text-white p-4">
                    <p className="text-center">© 2025 Utility Hub — Daniel Godoy</p>
                </footer>
            </body>
        </html>
    )
}
