import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Utility Hub - Apps created with Next.js - Daniel Godoy",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="flex flex-col min-h-screen">

                <Providers>
                    <main className="flex-1">
                        {children}
                    </main>
                </Providers>

                <footer className="bg-black text-white p-4">
                    <p className="text-center">© 2025 Utility Hub — <a href="https://github.com/DanielGodoyGalindo" className="hover:underline">Daniel Godoy</a></p>
                </footer>
            </body>
        </html>
    )
}
